ROUTINE RunScript
 #; We will run this routine to do the benchmark
Run()
{
 #; extract files if necessary from .data/in to .data/temp

 #; Start time
 Set startTime = $ZHOROLOG

 Set t=$ZH,sc=$ZF(-1,"/usr/irissys/bin/irispython /home/irisowner/dev/src/process.py")

 #; End time
 Set endTime = $ZHOROLOG
 #; Elapsed time in seconds
 Set elapsed = endTime - startTime
 Write "Elapsed time: ", elapsed, " seconds", !
}